version: '3'

services:
  lucasspider.agent1:
    image: 'lucasspider/agent:latest'
    restart: always
    container_name: lucasspider.agent1
    volumes:
      - ./agent1.json:/agent/appsettings.json
  lucasspider.agent2:
    image: 'lucasspider/agent:latest'
    restart: always
    container_name: lucasspider.agent2
    volumes:
      - ./agent2.json:/agent/appsettings.json