name: Package Hotfix Release

on:
  workflow_dispatch:
    inputs:
      reference:
          type: string
          required: true
          description: Hotfix Branch Name

jobs:
  startup:
    name: Startup
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-startup@main
        with:
          stage: production
          reference: ${{ github.event.inputs.reference }}
          token: ${{ github.token }}
          hotfix: true

  test:
    name: Test
    needs: [startup]
    uses: ./.github/workflows/test-job.yaml

  publish:
    name: Publish Package
    needs: [test]
    uses: ./.github/workflows/publish-job.yaml
    with:
      stage: production
    secrets: inherit

  release:
    name: Release
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
      - uses: NoorDigitalAgency/release-publish@main
        with:
          stage: production
          token: ${{ github.token }}

  post-hotfox:
    name: Post Hotfix
    needs: [release]
    uses: NoorDigitalAgency/.github/.github/workflows/post-hotfix.yaml@main
    with:
      hotfix_branch: ${{ github.event.inputs.reference }}
